/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class ATM extends javax.swing.JFrame {

    /**
     * Creates new form ATM
     */
    static int p = 0;
    
    public ATM(int pin) {
        initComponents();
        p = pin;
    }

    ATM() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t = new javax.swing.JTextField();
        d = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        e = new javax.swing.JButton();
        b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        l1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l1.setForeground(new java.awt.Color(242, 242, 242));
        l1.setText("              ENTER THE AMOUNT ");
        getContentPane().add(l1);
        l1.setBounds(230, 300, 320, 20);

        l2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        l2.setForeground(new java.awt.Color(242, 242, 242));
        getContentPane().add(l2);
        l2.setBounds(300, 370, 112, 16);
        getContentPane().add(t);
        t.setBounds(230, 340, 290, 22);

        d.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        d.setText("DEPOSIT");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });
        getContentPane().add(d);
        d.setBounds(200, 450, 130, 26);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("CASH WITHDRAW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 450, 152, 26);

        e.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        e.setText("EXIT");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });
        getContentPane().add(e);
        e.setBounds(200, 510, 130, 26);

        b.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b.setText("BALANCE CASH");
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        getContentPane().add(b);
        b.setBounds(370, 510, 150, 26);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\admin\\Documents\\NetBeansProjects\\Bank management system\\src\\icons\\atm.jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 920, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        // TODO add your handling code here:
         l2.setText("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/bank";
            String uname = "root";
            String pass = "divya05@yepse";
            Connection con = DriverManager.getConnection(url, uname, pass);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from login where pin = "+p+";");
            rs.next();
            int bal = Integer.parseInt(rs.getString("balance"));
            bal += Integer.parseInt(t.getText());
            int i = stmt.executeUpdate("update login set balance = "+bal+" where pin = "+p+"");
            if(i>0)
            {
                System.out.println("Row Updated");
            }
            con.close();
        } catch (Exception ex) {
            System.out.println("Exception" + ex);
        }
        t.setText("");
    }//GEN-LAST:event_dActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        l2.setText("");
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/bank";
            String uname = "root";
            String pass = "divya05@yepse";
            Connection con = DriverManager.getConnection(url, uname, pass);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from login where pin = "+p+";");
            rs.next();
            int bal = Integer.parseInt(rs.getString("balance"));
            if(bal - Integer.parseInt(t.getText()) < 0){
                l2.setText("Invalid Amount!!!");
                return;
            }
            bal -= Integer.parseInt(t.getText());
            int i = stmt.executeUpdate("update login set balance = "+bal+" where pin = "+p+"");
            if(i>0)
            {
                System.out.println("Row Updated");
            }
            con.close();
        } catch (Exception ex) {
            System.out.println("Exception" + ex);
        }
        t.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_eActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
         
        try {
            Class.forName("com.mysql.jdbc.Driver");
            String url = "jdbc:mysql://localhost:3306/bank";
            String uname = "root";
            String pass = "divya05@yepse";
            Connection con = DriverManager.getConnection(url, uname, pass);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from login where pin = "+p+";");
            rs.next();
            int bal = Integer.parseInt(rs.getString("balance"));
            // l2.setText("" + bal);
            
            
           int i = stmt.executeUpdate("update login set balance = "+bal+" where pin = "+p+"");
            if(i>0)
            {
                System.out.println("Row Updated");
                l2.setText("" + bal);
                return;
            }
            con.close();
        } catch (Exception ex) {
            System.out.println("Exception" + ex);
        }
        
           
    }//GEN-LAST:event_bActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM(p).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton d;
    private javax.swing.JButton e;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
